// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $aktuelle_sager_sager_ from "./routes/aktuelle-sager/[sager].tsx";
import * as $aktuelle_sager_index from "./routes/aktuelle-sager/index.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $kalender_index from "./routes/kalender/index.tsx";
import * as $kontakt_index from "./routes/kontakt/index.tsx";
import * as $om_os_index from "./routes/om-os/index.tsx";
import * as $politik_index from "./routes/politik/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/aktuelle-sager/[sager].tsx": $aktuelle_sager_sager_,
    "./routes/aktuelle-sager/index.tsx": $aktuelle_sager_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/kalender/index.tsx": $kalender_index,
    "./routes/kontakt/index.tsx": $kontakt_index,
    "./routes/om-os/index.tsx": $om_os_index,
    "./routes/politik/index.tsx": $politik_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Navbar.tsx": $Navbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
